version: 1.0.{build}

image: Visual Studio 2017

environment:
  matrix:
  - PLATFORM: msvc
  - PLATFORM: cygwin64
  - PLATFORM: mingw64

install:
  - call %APPVEYOR_BUILD_FOLDER%\install_%PLATFORM%.bat
  
build_script:
  - call %APPVEYOR_BUILD_FOLDER%\build_script_%PLATFORM%.bat

after_build:
  - call %APPVEYOR_BUILD_FOLDER%\after_build_%PLATFORM%.bat

test_script:
  - 'echo skip test'

artifacts:
  - path: swift_llvm_bin.tar.gz
    name: Swift-LLVM Binary
